name=input("enter your name : ")
age=int(input("enter your age : "))
height =float(input("enter your heignt :"))
weight=float(input("enter your weight : "))
course=input("enter the course you want to study : ")
print("------------------The student details you entered-------------------\n")
print(f"Name :: {name}")
print(f"Age :: {age}")
print(f"Height :: {height}")
print(f"Weight :: {weight}")
print(f"Course :: {course}")